### ISSUE TITLE
Revert local shuffle when it gets obsolete

### ISSUE THREAD

**Issue by naoyam** [naoyam/lbann#54]
Revert #53 when it becomes obsolete.

**Comment by naoyam** [comment]
@oyamay Can we revert this since we do not use local shuffle anymore?

**Comment by oyamay** [comment]
@naoyam I reverted the local shuffle function at eabdd576b1d0aaa668e248d037152f4fd93f82e8.

**Comment by naoyam** [comment]
@oyamay Thanks. Did you create a PR?

**Comment by oyamay** [comment]
I created #69 for this issue.

**Comment by naoyam** [comment]
Closed by #69
